version: "3.7"

services:
  front:
    build: ./front
    volumes:
      - type: bind
        source: "./front"
        target: "/front"
    tty: true
    env_file: .env
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002